use student_manager;

insert into LopHoc (maLopHoc) values("L1");
insert into MonHoc (maMonHoc) values("M1");
insert into MonHoc (maMonHoc) values("M2");
insert into MonHoc (maMonHoc) values("M3");
insert into MonHoc (maMonHoc) values("M4");
insert into MonHoc (maMonHoc) values("M5");
insert into MonHoc (maMonHoc) values("M6");
insert into MonHoc (maMonHoc) values("M7");
insert into MonHoc (maMonHoc) values("M8");
insert into SinhVien values("1712338", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712339", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712340", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712341", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712342", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712343", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712344", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712345", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712346", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712347", "Van Dat", "nam", "M1", "L1");
insert into SinhVien values("1712348", "Van Dat", "nam", "M1", "L1");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M1");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M2");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M3");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M4");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M5");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M6");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M7");
insert into MonHoc_SinhVien(mssv, maMonHoc) values("1712338", "M8");
select * from MonHoc_SinhVien;
select * from LopHoc;
