/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ltudjava.summer2020.pkg1712337.bt2.java.module;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.DiemDao;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.LopHocDao;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.MonHocDao;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.SinhVienDao;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.Diem;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.LopHoc;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.MonHoc;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.SinhVien;

/**
 *
 * @author user
 */
public class QLDIEM extends javax.swing.JFrame {

    /**
     * Creates new form QLSV
     */
    public QLDIEM() {
        initComponents();
        reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        csvChooser = new javax.swing.JFileChooser();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldMssv = new javax.swing.JTextField();
        textFieldKhac = new javax.swing.JTextField();
        textFieldGK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSinhVien = new javax.swing.JTable();
        importButton = new java.awt.Button();
        addButton = new java.awt.Button();
        refreshButton = new javax.swing.JButton();
        comboBoxLopShow = new javax.swing.JComboBox<>();
        comboBoxMaMonHoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textFieldTong = new javax.swing.JTextField();
        textFieldCK = new javax.swing.JTextField();
        comboBoxMaMonFill = new javax.swing.JComboBox<>();
        buttonUpdate = new javax.swing.JButton();
        labelDau = new javax.swing.JLabel();
        labelRot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("MSSV");

        jLabel2.setText("Mã Môn Học");

        jLabel3.setText("Điểm GK");

        jLabel4.setText("Điểm CK");

        jLabel5.setText("Điểm Khác");

        tabelSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSinhVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelSinhVien);

        importButton.setLabel("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        addButton.setLabel("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Reset");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        comboBoxLopShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxMaMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Điểm Tổng");

        comboBoxMaMonFill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        labelDau.setText("Đậu: 0%");

        labelRot.setText("Rớt: 100%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldMssv, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(textFieldGK, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(textFieldKhac, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(textFieldTong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(textFieldCK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(comboBoxMaMonFill, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonUpdate)
                                    .addComponent(refreshButton))
                                .addGap(10, 10, 10)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDau)
                        .addGap(68, 68, 68)
                        .addComponent(labelRot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxLopShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxLopShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDau)
                    .addComponent(labelRot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refreshButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textFieldMssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboBoxMaMonFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textFieldKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textFieldTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(buttonUpdate)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GiaoVuHome gv = new GiaoVuHome();
        this.setVisible(false);
        gv.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        resetSinhVienForm();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        DiemDao dao = new DiemDao();
        dao.create(getDiemFromForm());
        reloadData();
    }//GEN-LAST:event_addButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // TODO add your handling code here:
        DiemDao diemDao = new DiemDao();
        LopHocDao lopHocDao = new LopHocDao();
        MonHocDao monHocDao = new MonHocDao();
        SinhVienDao sinhVienDao = new SinhVienDao();
        if (csvChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            List<String> list = new ArrayList<>();
            try (BufferedReader br = Files.newBufferedReader(Paths.get(csvChooser.getSelectedFile().getAbsolutePath()))) {
                    //br returns as stream and convert it into a List
                    list = br.lines().collect(Collectors.toList());
            } catch (IOException e) {
                    e.printStackTrace();
            }
            String[] line1 = list.get(0).split("-");
            if (!lopHocDao.isExistLopHoc(line1[0])){
                lopHocDao.create(new LopHoc(list.get(0)));
            }
            if (monHocDao.getMonHocByMaMonHoc(line1[1]) == null){
                monHocDao.create(new MonHoc(line1[1], "", "", new LopHoc(line1[0])));
            }
            for (int i =2;i < list.size();i++){
                String[] line = list.get(i).split(",");
                SinhVien sv = new SinhVien(line[1], line[2], "", "", new LopHoc(line1[0]));
                if (sinhVienDao.getSinhVienByMSSV(line[1]) == null){
                    sinhVienDao.create(sv);
                }
                diemDao.create(new Diem(sv, monHocDao.getMonHocByMaMonHoc(line1[1]) , Float.valueOf(line[3]), Float.valueOf(line[4]), Float.valueOf(line[5]), Float.valueOf(line[6])));
            }
        }
        reloadData();
    }//GEN-LAST:event_importButtonActionPerformed

    
    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        DiemDao dao = new DiemDao();
        dao.update(getDiemFromForm());
        reloadData();
    }//GEN-LAST:event_buttonUpdateActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDIEM().setVisible(true);
            }
        });
    }
    
    private void reloadData(){
        reloadTable("All", "All");
        final LopHocDao lopHocDao = new LopHocDao();
        List<LopHoc> lhs = lopHocDao.getList();
        String[] lhData = new String[lhs.size()];
        String[] lhDataShowing = new String[lhs.size() + 1];
        lhDataShowing[0] = "All";
        for (int i=0;i<lhs.size();i++){
            lhData[i] = lhs.get(i).getMaLopHoc();
            lhDataShowing[i + 1] = lhs.get(i).getMaLopHoc();
        }
        MonHocDao monHocDao = new MonHocDao();
        List<MonHoc> monHocs = lopHocDao.getMonHocByMaLop("All");
        String[] mhData = new String[monHocs.size() + 1];
        String[] mhDataFill = new String[monHocs.size()];
        mhData[0] = "All";
        for (int i=0;i<monHocs.size();i++){
            mhData[i + 1] = monHocs.get(i).getMaMonHoc();
            mhDataFill[i]= monHocs.get(i).getMaMonHoc();
        }
        comboBoxMaMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(mhData));
        comboBoxMaMonFill.setModel(new javax.swing.DefaultComboBoxModel<>(mhDataFill));
        comboBoxLopShow.setModel(new javax.swing.DefaultComboBoxModel<>(lhDataShowing));
        comboBoxLopShow.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                //To change body of generated methods, choose Tools | Templates.
//                reloadData();
                List<MonHoc> monHocs = lopHocDao.getMonHocByMaLop(comboBoxLopShow.getSelectedItem().toString());
                String[] mhData = new String[monHocs.size() + 1];
                mhData[0] = "All";
                for (int i=0;i<monHocs.size();i++){
                    mhData[i + 1] = monHocs.get(i).getMaMonHoc();
                }
                comboBoxMaMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(mhData));
                reloadTable(comboBoxLopShow.getSelectedItem().toString(), comboBoxMaMonHoc.getSelectedItem().toString());
            }
        });
        
        comboBoxMaMonHoc.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                //To change body of generated methods, choose Tools | Templates.
//                reloadData();
                reloadTable(comboBoxLopShow.getSelectedItem().toString(), comboBoxMaMonHoc.getSelectedItem().toString());
            }
        });
    }
    
    private void reloadTable(String maLop, String maMon){
        DiemDao dao = new DiemDao();
        List<Diem> svData = dao.getDiemByMaLopMaMon(maLop, maMon);
        String[][] data = new String[svData.size()][8];
        int dau = 0;
        for (int i=0;i<svData.size();i++){
            data[i][0] = String.valueOf(i+1);
            data[i][1] = svData.get(i).getSinhVien().getMssv();
            data[i][2] = svData.get(i).getSinhVien().getHoTen();
            data[i][3] = String.valueOf(svData.get(i).getDiemGK());
            data[i][4] = String.valueOf(svData.get(i).getDiemCK());
            data[i][5] = String.valueOf(svData.get(i).getDiemKhac());
            data[i][6] = String.valueOf(svData.get(i).getDiemTong());
            if (svData.get(i).getDiemTong() >= 5.0){
                data[i][7] = "Đậu";
                dau += 1;
            }else{
                data[i][7] = "Rớt";
            }
        }
        labelDau.setText("Đậu: " + Math.round(dau*1.0/(svData.size())*100) + "%");
        labelRot.setText("Rớt: " + Math.round((svData.size() - dau)*1.0/(svData.size())*100) + "%");
        tabelSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "STT", "MSSV", "Họ Tên", "Điểm GK", "Điểm CK", "Điểm Khác", "Điểm Tổng", "Nhận Xét"
            }
        ));
    }
    
    private Diem getDiemFromForm(){
        Diem diem = new Diem();
        diem.setSinhVien((new SinhVienDao()).getSinhVienByMSSV(textFieldMssv.getText()));
        diem.setMonHoc((new MonHocDao()).getMonHocByMaMonHoc(comboBoxMaMonFill.getSelectedItem().toString()));
        diem.setDiemGK(Float.valueOf(textFieldGK.getText()));
        diem.setDiemCK(Float.valueOf(textFieldCK.getText()));
        diem.setDiemKhac(Float.valueOf(textFieldCK.getText()));
        diem.setDiemTong(Float.valueOf(textFieldTong.getText()));
        return diem;
    }
    
    private void resetSinhVienForm(){
        textFieldMssv.setText("");
        textFieldGK.setText("");
        textFieldCK.setText("");
        textFieldKhac.setText("");
        textFieldTong.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> comboBoxLopShow;
    private javax.swing.JComboBox<String> comboBoxMaMonFill;
    private javax.swing.JComboBox<String> comboBoxMaMonHoc;
    private javax.swing.JFileChooser csvChooser;
    private java.awt.Button importButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDau;
    private javax.swing.JLabel labelRot;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable tabelSinhVien;
    private javax.swing.JTextField textFieldCK;
    private javax.swing.JTextField textFieldGK;
    private javax.swing.JTextField textFieldKhac;
    private javax.swing.JTextField textFieldMssv;
    private javax.swing.JTextField textFieldTong;
    // End of variables declaration//GEN-END:variables
}
