/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ltudjava.summer2020.pkg1712337.bt2.java.module;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.MonHocDao;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.PhucKhaoDao;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.PhucKhaoDiemDao;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.SinhVienDao;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.MonHoc;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.PhucKhao;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.PhucKhaoDiem;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.SinhVien;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.User;
import ltudjava.summer2020.pkg1712337.bt2.java.util.FileUtils;

/**
 *
 * @author user
 */
public class QLPK extends javax.swing.JFrame {

    /**
     * Creates new form QLPK
     */
    public QLPK() {
        initComponents();
        reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBoxMonHoc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNgayBD = new javax.swing.JTextField();
        jTextFieldNgayKT = new javax.swing.JTextField();
        jButtonSubmitPK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Đơn phúc khảo");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel2.setText("Thời gian bắt đầu (dd/mm/yyyy)");

        jLabel3.setText("Thời gian kết thúc (dd/mm/yyyy)");

        jButtonSubmitPK.setText("Tạo đợt phúc khảo");
        jButtonSubmitPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitPKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSubmitPK))
                    .addComponent(jLabel3))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubmitPK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        GiaoVuHome gv = new GiaoVuHome();
        gv.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSubmitPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitPKActionPerformed
        try {
            // TODO add your handling code here:
            PhucKhaoDao phucKhaoDao = new PhucKhaoDao();
            String pattern = "dd/MM/yyyy";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            phucKhaoDao.create(new PhucKhao(jComboBoxMonHoc.getSelectedItem().toString(), simpleDateFormat.parse(jTextFieldNgayBD.getText()), simpleDateFormat.parse(jTextFieldNgayKT.getText())));
        } catch (ParseException ex) {
            Logger.getLogger(QLPK.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Làm ơn nhập đúng format Date", "Error!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubmitPKActionPerformed

    private void reloadData(){
        MonHocDao monHocDao = new MonHocDao();
        List<MonHoc> monHocs = monHocDao.getList();
        String[] mhData = new String[monHocs.size() + 1];
        mhData[0] = "All";
        for (int i=0;i<monHocs.size();i++){
            mhData[i + 1] = monHocs.get(i).getMaMonHoc();
        }
        jComboBoxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(mhData));
        reloadTable();
    }
    
    private void reloadTable(){
        PhucKhaoDiemDao dao = new PhucKhaoDiemDao();
        List<PhucKhaoDiem> svData = dao.getList();
        String[][] data = new String[svData.size()][8];
        int dau = 0;
        for (int i=0;i<svData.size();i++){
            data[i][0] = String.valueOf(i+1);
            data[i][1] = svData.get(i).getMssv();
            data[i][2] = svData.get(i).getHoTen();
            data[i][3] = svData.get(i).getBangPhucKhao().getMaMonHoc();
            data[i][4] = svData.get(i).getCotDiem();
            data[i][5] = String.valueOf(svData.get(i).getDiemMongMuon());
            data[i][6] = svData.get(i).getLyDo();
            data[i][7] = svData.get(i).getTinhTrang();
        }
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "STT", "MSSV", "Họ Tên", "Môn", "Cột điểm cần phúc khảo", "Điểm mong muốn", "Lý do", "Tình trạng"
            }
        ));
        jTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                PhucKhaoDiemDao dao = new PhucKhaoDiemDao();
                PhucKhaoDao phucKhaoDao = new PhucKhaoDao();
                PhucKhao bangPhucKhao = phucKhaoDao.getPhucKhaoByMaMonHoc(jTable.getValueAt(jTable.getSelectedRow(), 3).toString());
                PhucKhaoDiem phucKhaoDiem = new PhucKhaoDiem(
                        jTable.getValueAt(jTable.getSelectedRow(), 1).toString(), 
                        jTable.getValueAt(jTable.getSelectedRow(), 2).toString(), 
                        bangPhucKhao, 
                        jTable.getValueAt(jTable.getSelectedRow(), 4).toString(), 
                        Float.valueOf(jTable.getValueAt(jTable.getSelectedRow(), 5).toString()), 
                        jTable.getValueAt(jTable.getSelectedRow(), 6).toString(), 
                        jTable.getValueAt(jTable.getSelectedRow(), 7).toString());
                setVisible(false);
                ChinhSuaPhucKhao c = new ChinhSuaPhucKhao();
                c.setPhucKhaoDiem(phucKhaoDiem);
                c.setVisible(true);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLPK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSubmitPK;
    private javax.swing.JComboBox<String> jComboBoxMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldNgayBD;
    private javax.swing.JTextField jTextFieldNgayKT;
    // End of variables declaration//GEN-END:variables
}
