/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ltudjava.summer2020.pkg1712337.bt2.java.module;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.DiemDao;
import ltudjava.summer2020.pkg1712337.bt2.java.dao.MonHocDao;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.Diem;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.MonHoc;
import ltudjava.summer2020.pkg1712337.bt2.java.pojo.User;
import ltudjava.summer2020.pkg1712337.bt2.java.util.FileUtils;

/**
 *
 * @author user
 */
public class SVXemDiem extends javax.swing.JFrame {

    /**
     * Creates new form SVXemDiem
     */
    public SVXemDiem() {
        initComponents();
        reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jComboBoxMonHoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDiem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jComboBoxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonHocActionPerformed(evt);
            }
        });

        jTableDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDiem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(247, 247, 247)
                        .addComponent(jComboBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(jComboBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SinhVienHome sv = new SinhVienHome();
        sv.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jComboBoxMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonHocActionPerformed

    private void reloadData(){
        User sv = FileUtils.getObject(User.class, "user.txt");
        MonHocDao monHocDao = new MonHocDao();
        List<MonHoc> monHocs = monHocDao.getList();
        String[] mhData = new String[monHocs.size() + 1];
        mhData[0] = "All";
        for (int i=0;i<monHocs.size();i++){
            mhData[i + 1] = monHocs.get(i).getMaMonHoc();
        }
        jComboBoxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(mhData));
        jComboBoxMonHoc.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                reloadTable(sv.getUserName(), jComboBoxMonHoc.getSelectedItem().toString());
            }
        });
        reloadTable(sv.getUserName(), "All");
    }
    
    private void reloadTable(String mssv, String maMon){
        DiemDao diemDao = new DiemDao();
        List<Diem> diems = diemDao.getDiemByMssvMonHoc(mssv, maMon);
        String[][] data = new String[diems.size()][8];
        for (int i=0;i<diems.size();i++){
            data[i][0] = String.valueOf(i+1);
            data[i][1] = diems.get(i).getSinhVien().getMssv();
            data[i][2] = diems.get(i).getSinhVien().getHoTen();
            data[i][3] = String.valueOf(diems.get(i).getDiemGK());
            data[i][4] = String.valueOf(diems.get(i).getDiemCK());
            data[i][5] = String.valueOf(diems.get(i).getDiemKhac());
            data[i][6] = String.valueOf(diems.get(i).getDiemTong());
            if (diems.get(i).getDiemTong() >= 5.0){
                data[i][7] = "Đậu";
            }else{
                data[i][7] = "Rớt";
            }
        }
        jTableDiem.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "STT", "MSSV", "Họ Tên", "Điểm GK", "Điểm CK", "Điểm Khác", "Điểm Tổng", "Nhận Xét"
            }
        ));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVXemDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> jComboBoxMonHoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDiem;
    // End of variables declaration//GEN-END:variables
}
